name: "Minecraft Bedrock Server"
description: "Minecraft Bedrock Server tailored for Home Assistant with worlds accessible via SFTP"
version: "1.0.28"
slug: "minecraft_bedrock_server"
url: https://github.com/sjauijn/minecraft-bedrock-server-HAOS/
apparmor: true
init: false
startup: application
ingress: true
ingress_port: 8789
panel_icon: mdi:minecraft
panel_title: "Minecraft Server"
host_network: true
arch:
  - amd64
map:
  - share:rw
  - addon_config:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
